// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnVMqNNZ9D7_c5GxcIK6ZE-N9aU96HMas',
    appId: '1:606840882496:web:b5ebc913e829154f03a6a5',
    messagingSenderId: '606840882496',
    projectId: 'test122-ba9a4',
    authDomain: 'test122-ba9a4.firebaseapp.com',
    storageBucket: 'test122-ba9a4.appspot.com',
    measurementId: 'G-0R1ZZHP6CD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNsu4gbwoXRkFFLfUsDmYzoLK2D1KSWuM',
    appId: '1:606840882496:android:4b25324f02613bf403a6a5',
    messagingSenderId: '606840882496',
    projectId: 'test122-ba9a4',
    storageBucket: 'test122-ba9a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuBAqi4BaTaSoWzL4tpChjc8GtOvBynTs',
    appId: '1:606840882496:ios:ed586ab92a97b05c03a6a5',
    messagingSenderId: '606840882496',
    projectId: 'test122-ba9a4',
    storageBucket: 'test122-ba9a4.appspot.com',
    iosClientId: '606840882496-b04njg9fju0oalphd35pempj9cvcid0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.nkorr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuBAqi4BaTaSoWzL4tpChjc8GtOvBynTs',
    appId: '1:606840882496:ios:f273fe66197dfd9803a6a5',
    messagingSenderId: '606840882496',
    projectId: 'test122-ba9a4',
    storageBucket: 'test122-ba9a4.appspot.com',
    iosClientId: '606840882496-70j7ogvvbh83jkvn6gota8afm2obdmdq.apps.googleusercontent.com',
    iosBundleId: 'com.example.nkorr.RunnerTests',
  );
}
